### ISSUE TITLE
wie erstellst du diese Kommentare [FRAGE, kein Bug]

### ISSUE THREAD

**Issue by 3ele-projects** [Lightweb-Media/theme_photovoltaik#3]
https://github.com/Lightweb-Media/theme_photovoltaik/blob/e4803c506157e7c5d44fb2e777e963f8bfc0f246/functions.php#L115

**Comment by ReneKutter** [comment]
Hatte den Code teilweise ausm Internet übernommen. Das @uses war schon und ich dachte ich lasse das drin.
