### ISSUE TITLE
Text Domaine auch nutzen

### ISSUE THREAD

**Issue by 3ele-projects** [Lightweb-Media/theme_photovoltaik#4]
https://github.com/Lightweb-Media/theme_photovoltaik/blob/e4803c506157e7c5d44fb2e777e963f8bfc0f246/style.css#L9

**Comment by ReneKutter** [comment]
Hab ich genutzt. Hier zum Beispiel:
https://github.com/Lightweb-Media/theme_photovoltaik/blob/e7ca488e44dd2fbb0378077ca36b15788306bdb2/shortcodes.php#L19
